name: Java CI with Gradle

on:
  push:
    branches: [ "develop", "feature/MAP-40" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Make application.properties
        run: |
          cd ./src/main
          mkdir resources
          cd ./resources
          touch ./application.properties
          echo "spring.datasource.url=$DB_URL" >> ./application.properties
          echo "spring.datasource.username=$DB_USER" >> ./application.properties
          echo "spring.datasource.password=$DB_PW" >> ./application.properties
          echo "spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver" >> ./application.properties
          echo "jpa.hibernate.ddl-auto=none" >> ./application.properties
        shell: bash
        env:
          DB_URL: ${{secrets.DB_URL}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PW: ${{secrets.DB_PW}}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --exclude-task test
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Make application.properties
        run: |
          cd ./src/main
          mkdir resources
          cd ./resources
          touch ./application.properties
          echo "spring.datasource.url=$DB_URL" >> ./application.properties
          echo "spring.datasource.username=$DB_USER" >> ./application.properties
          echo "spring.datasource.password=$DB_PW" >> ./application.properties
          echo "spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver" >> ./application.properties
          echo "jpa.hibernate.ddl-auto=none" >> ./application.properties
        shell: bash
        env:
          DB_URL: ${{secrets.DB_URL}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PW: ${{secrets.DB_PW}}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test