name: Java CI with Gradle

on:
  push:
    branches: [ "develop", "feature/MAP-40" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Make application.properties
        run: |
          cd ./src/main
          mkdir resources
          cd ./resources
          touch ./application.properties
          echo "DB_SETTING" >> ./application.properties
          ls -al
          cat ./application.properties
        shell: bash
        env:
          DB_SETTING: ${{DB_SETTING}}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test